Init placeholder workflows.

diff --git a/.github/workflows/build-compose.yml b/.github/workflows/build-compose.yml
--- a/.github/workflows/build-compose.yml
+++ b/.github/workflows/build-compose.yml
@@ -13,16 +13,28 @@ jobs:
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
 
-    - name: Build and run Docker Compose
-      run: |
-        docker-compose up --build -d
+    # Need to configure default .env variables and localstack emulation 
 
-    - name: Check running containers
-      run: |
-        docker-compose ps
-        if [[ $(docker-compose ps | grep 'fastapi') ]]; then
-            echo "FastAPI service is up."
-        else
-            echo "FastAPI failed to run."
-            exit 1
-        fi
+    # - name: Build and run Docker Compose
+    #   run: |
+    #     docker-compose up --build -d
+
+    # - name: Check running server
+    #   run: |
+    #     docker-compose ps
+    #     if [[ $(docker-compose ps | grep 'server') ]]; then
+    #         echo "FastAPI service is up."
+    #     else
+    #         echo "FastAPI failed to run."
+    #         exit 1
+    #     fi
+
+    # - name: Check running ui
+    #   run: |
+    #     docker-compose ps
+    #     if [[ $(docker-compose ps | grep 'ui') ]]; then
+    #         echo "React app is up."
+    #     else
+    #         echo "React app failed to run."
+    #         exit 1
+    #     fi
